version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: db
    networks:
      - cgnet
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./tools/database:/docker-entrypoint-initdb.d
    env_file:
      - .build.env
      - .docker.env

  client:
    extends:
      file: .docker/compose/common/preset.app.prod.yml
      service: app
    build:
      dockerfile: apps/client/Dockerfile
      context: .
    container_name: client
    networks:
      - cgnet
    ports:
      - 3000:80

  server:
    extends:
      file: .docker/compose/common/preset.app.prod.yml
      service: app
    build:
      dockerfile: apps/server/Dockerfile
      context: .
    container_name: server
    networks:
      - cgnet
    ports:
      - 6868:6868

networks:
  cgnet:
    driver: bridge
