version: '3.9'

services:
  client:
    build:
      dockerfile: apps/client/Dockerfile
      context: .
    container_name: client
    restart: always
    env_file:
      - .env
      - .docker/.override.env
    networks:
      - cgnet
    ports:
      - 3000:80

  gateway:
    build:
      dockerfile: apps/server/gateway/Dockerfile
      context: .
    container_name: gateway
    depends_on:
      - kafka
      - mysql
    networks:
      - cgnet
    ports:
      - 6868:6868
    restart: always
    env_file:
      - .env
      - .docker/.override.env

  service-code-executor:
    build:
      dockerfile: apps/server/service-code-executor/Dockerfile
      context: .
    container_name: service-code-executor
    depends_on:
      - kafka
    networks:
      - cgnet
    restart: always
    env_file:
      - .env
      - .docker/.override.env
