export { AiOutlineClose,AiOutlineInfoCircle, AiOutlineHtml5 } from 'react-icons/ai'
export { BsJournals,BsSearch } from 'react-icons/bs'
export { GoTerminal } from 'react-icons/go'
export { GrClear } from 'react-icons/gr'
export { LuTestTube2 } from 'react-icons/lu'
export { MdFindReplace } from 'react-icons/md'
export { SlInfo,SlSizeFullscreen } from 'react-icons/sl'
export { TfiSettings } from 'react-icons/tfi'
export { VscPlay } from 'react-icons/vsc'
