name: CodeGear CI > build
on:
  pull_request:
    branches: [ master ]
  push: [ master ]
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    name: Creating a Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Creating a Production Build
        run: yarn dlx nx run-many -t=build -p client server --parallel=8

  build-storybook:
    name: Building and deploying storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Building storybook
        run: yarn dlx nx run ui:storybook:build
