name: code-gear > build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  push-build:
    needs: [build]
    name: Pushing workflow to build branch
    runs-on: ubuntu-latest
    steps:
      - name: using setup script
        uses: ./.github/conf/setup.yml

      - name: Pushing to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"

  push-storybook:
    needs: [build]
    name: Building and deploying storybook
    runs-on: ubuntu-latest
    steps:
      - name: using setup script
        uses: ./.github/conf/setup.yml

      - name: Pushing to build-storybook branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/storybook/ui
          branch: storybook-build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
