name: code-gear > lint
on:
  pull_request:
    branches:
      - master
      - ci-testing
  push:
    branches:
      - master
      - ci-testing
permissions:
  contents: write

jobs:
  lint:
    name: Linting project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: using setup script
        uses: ./.github/conf/setup.yml

      - name: Linting project
        run: yarn dlx nx run root:lint
