name: CodeGear CI > lint
on:
  pull_request:
    branches: [ master ]
  push: null
permissions:
  contents: write

jobs:
  lint:
    name: Linting project
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Linting project
        run: yarn run lint
