name: code-gear > lint
on:
  pull_request:
    branches: [ master ]
  push: [ master ]
permissions:
  contents: write

jobs:
  lint:
    name: Linting project
    runs-on: ubuntu-latest
    steps:
      - name: using setup script
        uses: ./.github/conf/setup.yml

      - name: Linting project
        run: yarn dlx nx run root:lint
