name: CodeGear CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ develop ]
permissions:
  contents: write
jobs:
  linting:
    name: Linting project
    runs-on: ubuntu-latest
    steps:
      # Node.js and pnpm setup
      - uses: actions/checkout@v3
      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      # Installing deps
      - name: Installing dependencies
        run: yarn install
      # Main rules
      - name: Linting project
        run: yarn run lint
  building:
    name: Creating a Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Node.js and pnpm setup
      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
        # Installing deps
      - name: Installing dependencies
        run: yarn install
        # Main rules
      - name: Creating a Production Build
        run: yarn run build
      - name: Pushing to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
