name: CodeGear CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: []
permissions:
  contents: write
jobs:
  linting:
    name: linting project
    runs-on: ubuntu-latest
    steps:
      # Node.js and yarn setup
      - uses: actions/checkout@v3
      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'yarn'
      # Installing deps
      - name: Installing dependencies
        run: yarn install
      # Main rules
      - name: Linting project
        run: yarn run lint
  building:
    name: creating a production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Node.js and yarn setup
      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'yarn'
        # Installing deps
      - name: Installing dependencies
        run: yarn install
        # Main rules
      - name: Creating a Production Build
        run: yarn run build
      - name: Pushing to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
  build-storybook:
    name: building storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Node.js and yarn setup
      - name: Installing Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'yarn'
        # Installing deps
      - name: Installing dependencies
        run: yarn install
        # Main rules
      - name: Building storybook
        run: yarn dlx nx run ui:storybook:build
      - name: Pushing to build-storybook branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: storybook-build
          build_dir: dist/storybook/ui
          commit_message: 'chore(deploy): storybook'
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
