name: code-gear > tests
on:
  pull_request:
    branches:
      - master
      - ci-testing
  push:
    branches:
      - master
      - ci-testing
permissions:
  contents: write

jobs:
  build-storybook:
    uses: ./.github/workflows/build.yml
  test-storybook:

    name: testing storybook
    needs: [build-storybook]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: using setup script
        uses: Gearonix/code-gear/.github/conf/setup.yml

      - name: Testing storybook in production
        run: yarn dlx nx run ui:storybook:test:production
  test:
    name: testing project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: using setup script
        uses: Gearonix/code-gear/.github/conf/setup.yml
